// AUTO-GENERATED from Twilio_SMS_Kosten_pro Land.csv — do not edit by hand.
// Regenerate when Twilio prices change. costUsd = outbound SMS purchase
// price per segment (USD). Customer price is derived below (FX × markup).
export interface SmsRate {
  name: string;
  costUsd: number;
}

export const SMS_RATES: Record<string, SmsRate> = {
  AD: { name: "Andorra", costUsd: 0.1464 },
  AE: { name: "United Arab Emirates", costUsd: 0.133 },
  AF: { name: "Afghanistan", costUsd: 0.446 },
  AG: { name: "Antigua And Barbuda", costUsd: 0.2384 },
  AI: { name: "Anguilla", costUsd: 0.2415 },
  AL: { name: "Albania", costUsd: 0.1167 },
  AM: { name: "Armenia", costUsd: 0.2996 },
  AO: { name: "Angola", costUsd: 0.3062 },
  AR: { name: "Argentina", costUsd: 0.1034 },
  AS: { name: "American Samoa", costUsd: 0.1881 },
  AT: { name: "Austria", costUsd: 0.0979 },
  AU: { name: "Australia", costUsd: 0.0515 },
  AW: { name: "Aruba", costUsd: 0.2789 },
  AZ: { name: "Azerbaijan", costUsd: 0.411 },
  BA: { name: "Bosnia And Herzegovina", costUsd: 0.511 },
  BB: { name: "Barbados", costUsd: 0.2624 },
  BD: { name: "Bangladesh", costUsd: 0.5962 },
  BF: { name: "Burkina Faso", costUsd: 0.3208 },
  BG: { name: "Bulgaria", costUsd: 0.1699 },
  BH: { name: "Bahrain", costUsd: 0.0386 },
  BI: { name: "Burundi", costUsd: 0.5088 },
  BM: { name: "Bermuda", costUsd: 0.263 },
  BN: { name: "Brunei", costUsd: 0.117 },
  BO: { name: "Bolivia", costUsd: 0.2215 },
  BR: { name: "Brazil", costUsd: 0.054 },
  BS: { name: "Bahamas", costUsd: 0.0904 },
  BT: { name: "Bhutan", costUsd: 0.4007 },
  BW: { name: "Botswana", costUsd: 0.158 },
  BY: { name: "Belarus", costUsd: 0.2521 },
  CA: { name: "Canada", costUsd: 0.0083 },
  CD: { name: "Congo, Democratic Republic", costUsd: 0.2453 },
  CF: { name: "Central African Republic", costUsd: 0.2584 },
  CG: { name: "Congo, Republic", costUsd: 0.2659 },
  CH: { name: "Switzerland", costUsd: 0.0855 },
  CI: { name: "Cote D'ivoire", costUsd: 0.3192 },
  CK: { name: "Cook Islands", costUsd: 0.428 },
  CL: { name: "Chile", costUsd: 0.1069 },
  CM: { name: "Cameroon", costUsd: 0.2448 },
  CN: { name: "China", costUsd: 0.0448 },
  CO: { name: "Colombia", costUsd: 0.039 },
  CR: { name: "Costa Rica", costUsd: 0.0699 },
  CU: { name: "Cuba", costUsd: 0.636 },
  CY: { name: "Cyprus", costUsd: 0.0524 },
  CZ: { name: "Czech Republic", costUsd: 0.0673 },
  DE: { name: "Germany", costUsd: 0.0885 },
  DK: { name: "Denmark", costUsd: 0.0592 },
  DM: { name: "Dominica", costUsd: 0.2533 },
  DO: { name: "Dominican Republic", costUsd: 0.1308 },
  DZ: { name: "Algeria", costUsd: 0.273 },
  EC: { name: "Ecuador", costUsd: 0.339 },
  EE: { name: "Estonia", costUsd: 0.0958 },
  ER: { name: "Eritrea", costUsd: 0.1236 },
  ES: { name: "Spain", costUsd: 0.0891 },
  ET: { name: "Ethiopia", costUsd: 0.3425 },
  FI: { name: "Finland", costUsd: 0.0779 },
  FJ: { name: "Fiji", costUsd: 0.2052 },
  FK: { name: "Falkland Islands (Malvinas)", costUsd: 0.264 },
  FR: { name: "France", costUsd: 0.0662 },
  GA: { name: "Gabon", costUsd: 0.2804 },
  GB: { name: "United Kingdom", costUsd: 0.0437 },
  GD: { name: "Grenada", costUsd: 0.2379 },
  GE: { name: "Georgia", costUsd: 0.1538 },
  GF: { name: "French Guiana", costUsd: 0.2065 },
  GH: { name: "Ghana", costUsd: 0.2299 },
  GI: { name: "Gibraltar", costUsd: 0.1183 },
  GL: { name: "Greenland", costUsd: 0.0891 },
  GM: { name: "Gambia", costUsd: 0.2337 },
  GN: { name: "Guinea", costUsd: 0.3444 },
  GP: { name: "Guadeloupe", costUsd: 0.2065 },
  GQ: { name: "Equatorial Guinea", costUsd: 0.2705 },
  GR: { name: "Greece", costUsd: 0.0778 },
  GT: { name: "Guatemala", costUsd: 0.164 },
  GW: { name: "Guinea-bissau", costUsd: 0.2938 },
  GY: { name: "Guyana", costUsd: 0.2459 },
  HK: { name: "Hong Kong", costUsd: 0.0608 },
  HN: { name: "Honduras", costUsd: 0.1833 },
  HR: { name: "Croatia", costUsd: 0.0861 },
  HT: { name: "Haiti", costUsd: 0.2869 },
  HU: { name: "Hungary", costUsd: 0.1019 },
  ID: { name: "Indonesia", costUsd: 0.3605 },
  IE: { name: "Ireland", costUsd: 0.0707 },
  IL: { name: "Israel", costUsd: 0.0485 },
  IN: { name: "India", costUsd: 0.0832 },
  IQ: { name: "Iraq", costUsd: 0.3018 },
  IR: { name: "Iran", costUsd: 0.305 },
  IS: { name: "Iceland", costUsd: 0.0783 },
  IT: { name: "Italy", costUsd: 0.0813 },
  JM: { name: "Jamaica", costUsd: 0.1741 },
  JO: { name: "Jordan", costUsd: 0.2182 },
  JP: { name: "Japan", costUsd: 0.0843 },
  KE: { name: "Kenya", costUsd: 0.1831 },
  KG: { name: "Kyrgyzstan", costUsd: 0.3045 },
  KH: { name: "Cambodia", costUsd: 0.1695 },
  KM: { name: "Comoros", costUsd: 0.2928 },
  KN: { name: "Saint Kitts And Nevis", costUsd: 0.2358 },
  KW: { name: "Kuwait", costUsd: 0.1099 },
  KY: { name: "Cayman Islands", costUsd: 0.1498 },
  KZ: { name: "Kazakhstan", costUsd: 0.2696 },
  LA: { name: "Laos", costUsd: 0.12 },
  LB: { name: "Lebanon", costUsd: 0.2849 },
  LC: { name: "Saint Lucia", costUsd: 0.2404 },
  LI: { name: "Liechtenstein", costUsd: 0.087 },
  LK: { name: "Sri Lanka", costUsd: 0.409 },
  LR: { name: "Liberia", costUsd: 0.202 },
  LS: { name: "Lesotho", costUsd: 0.254 },
  LT: { name: "Lithuania", costUsd: 0.0558 },
  LU: { name: "Luxembourg", costUsd: 0.0673 },
  LV: { name: "Latvia", costUsd: 0.1143 },
  LY: { name: "Libya", costUsd: 0.496 },
  MC: { name: "Monaco", costUsd: 0.1856 },
  MD: { name: "Moldova", costUsd: 0.1474 },
  MG: { name: "Madagascar", costUsd: 0.433 },
  MK: { name: "North Macedonia", costUsd: 0.1003 },
  ML: { name: "Mali", costUsd: 0.2866 },
  MM: { name: "Myanmar", costUsd: 0.346 },
  MN: { name: "Mongolia", costUsd: 0.2957 },
  MO: { name: "Macau", costUsd: 0.1209 },
  MQ: { name: "Martinique", costUsd: 0.2065 },
  MR: { name: "Mauritania", costUsd: 0.3618 },
  MS: { name: "Montserrat", costUsd: 0.2525 },
  MT: { name: "Malta", costUsd: 0.0765 },
  MU: { name: "Mauritius", costUsd: 0.2664 },
  MV: { name: "Maldives", costUsd: 0.248 },
  MW: { name: "Malawi", costUsd: 0.3067 },
  MY: { name: "Malaysia", costUsd: 0.1073 },
  MZ: { name: "Mozambique", costUsd: 0.417 },
  NA: { name: "Namibia", costUsd: 0.1562 },
  NC: { name: "New Caledonia", costUsd: 0.328 },
  NE: { name: "Niger", costUsd: 0.335 },
  NG: { name: "Nigeria", costUsd: 0.2002 },
  NI: { name: "Nicaragua", costUsd: 0.223 },
  NL: { name: "Netherlands", costUsd: 0.0868 },
  NO: { name: "Norway", costUsd: 0.07 },
  NP: { name: "Nepal", costUsd: 0.4838 },
  NZ: { name: "New Zealand", costUsd: 0.1176 },
  OM: { name: "Oman", costUsd: 0.144 },
  PA: { name: "Panama", costUsd: 0.1534 },
  PE: { name: "Peru", costUsd: 0.127 },
  PF: { name: "French Polynesia", costUsd: 0.4064 },
  PG: { name: "Papua New Guinea", costUsd: 0.474 },
  PH: { name: "Philippines", costUsd: 0.3613 },
  PK: { name: "Pakistan", costUsd: 0.361 },
  PL: { name: "Poland", costUsd: 0.0466 },
  PM: { name: "St. Pierre And Miquelon", costUsd: 0.454 },
  PR: { name: "Puerto Rico", costUsd: 0.0083 },
  PS: { name: "Palestine", costUsd: 0.3614 },
  PT: { name: "Portugal", costUsd: 0.0595 },
  PY: { name: "Paraguay", costUsd: 0.086 },
  QA: { name: "Qatar", costUsd: 0.136 },
  RE: { name: "Reunion", costUsd: 0.2065 },
  RO: { name: "Romania", costUsd: 0.0823 },
  RS: { name: "Serbia", costUsd: 0.1685 },
  RU: { name: "Russia", costUsd: 0.212 },
  RW: { name: "Rwanda", costUsd: 0.2397 },
  SA: { name: "Saudi Arabia", costUsd: 0.1032 },
  SD: { name: "Sudan", costUsd: 0.2847 },
  SE: { name: "Sweden", costUsd: 0.0697 },
  SG: { name: "Singapore", costUsd: 0.0554 },
  SI: { name: "Slovenia", costUsd: 0.0788 },
  SK: { name: "Slovakia", costUsd: 0.096 },
  SL: { name: "Sierra Leone", costUsd: 0.2695 },
  SN: { name: "Senegal", costUsd: 0.2975 },
  SO: { name: "Somalia", costUsd: 0.2059 },
  SR: { name: "Suriname", costUsd: 0.2095 },
  SS: { name: "South Sudan", costUsd: 0.2847 },
  SV: { name: "El Salvador", costUsd: 0.299 },
  SX: { name: "Sint Maarten", costUsd: 0.2263 },
  SY: { name: "Syria", costUsd: 0.222 },
  SZ: { name: "Swaziland", costUsd: 0.1562 },
  TC: { name: "Turks And Caicos Islands", costUsd: 0.2416 },
  TD: { name: "Chad", costUsd: 0.4543 },
  TG: { name: "Togo", costUsd: 0.2154 },
  TH: { name: "Thailand", costUsd: 0.057 },
  TJ: { name: "Tajikistan", costUsd: 0.2596 },
  TL: { name: "Timor-leste", costUsd: 0.147 },
  TM: { name: "Turkmenistan", costUsd: 0.217 },
  TN: { name: "Tunisia", costUsd: 0.31 },
  TO: { name: "Tonga", costUsd: 0.2424 },
  TR: { name: "Turkey", costUsd: 0.042 },
  TT: { name: "Trinidad And Tobago", costUsd: 0.1749 },
  TW: { name: "Taiwan", costUsd: 0.0764 },
  TZ: { name: "Tanzania", costUsd: 0.1913 },
  UA: { name: "Ukraine", costUsd: 0.201 },
  UG: { name: "Uganda", costUsd: 0.3137 },
  US: { name: "United States", costUsd: 0.0083 },
  UY: { name: "Uruguay", costUsd: 0.126 },
  UZ: { name: "Uzbekistan", costUsd: 0.297 },
  VC: { name: "Saint Vincent And The Grenadines", costUsd: 0.2469 },
  VE: { name: "Venezuela", costUsd: 0.0845 },
  VG: { name: "Virgin Islands, British", costUsd: 0.2362 },
  VN: { name: "Vietnam", costUsd: 0.136 },
  XK: { name: "Kosovo", costUsd: 0.2148 },
  YE: { name: "Yemen", costUsd: 0.269 },
  ZA: { name: "South Africa", costUsd: 0.0981 },
  ZM: { name: "Zambia", costUsd: 0.274 },
  ZW: { name: "Zimbabwe", costUsd: 0.2002 },
};

/** USD→EUR FX baked into customer prices (bump + redeploy when it drifts). */
export const SMS_FX_USD_EUR = 0.92;
/** Customer markup over the Twilio purchase cost (operator decision). */
export const SMS_MARKUP = 1.5;

/**
 * Customer price for one SMS segment to `countryCode`, in EUR minor units
 * (cents), rounded up. null when the country is not in the rate table.
 */
export function smsCustomerPriceMinor(countryCode: string): number | null {
  const r = SMS_RATES[countryCode];
  if (!r) return null;
  return Math.ceil(r.costUsd * SMS_FX_USD_EUR * SMS_MARKUP * 100);
}
