-- =============================================================================
-- Row-Level Security policies
-- =============================================================================
-- This migration is applied AFTER all table-creation migrations generated by
-- drizzle-kit. Filename is `9999_` so it sorts last.
--
-- Rules:
--   - All tenant-scoped tables have RLS enabled.
--   - A user can SELECT rows of any tenant they belong to (via memberships).
--   - Mutations (INSERT/UPDATE/DELETE) go through our API using the SERVICE
--     ROLE key, which bypasses RLS. The API layer enforces tenant scoping in
--     code, with the database as a defense-in-depth backup.
--   - The `users` table is special: a user can only SELECT their own row.
--
-- If you want users to insert/update directly from the client (e.g. for
-- realtime-driven optimistic UI), add per-table WITH CHECK policies here.
-- =============================================================================

-- ─── Helper: stable function returning the current user's tenant IDs ────────
CREATE OR REPLACE FUNCTION public.current_user_tenant_ids()
RETURNS SETOF UUID
LANGUAGE sql
STABLE
SECURITY DEFINER
SET search_path = public
AS $$
  SELECT tenant_id
  FROM public.memberships
  WHERE user_id = auth.uid()
$$;

-- ─── Mirror Supabase auth.users into public.users on signup ─────────────────
CREATE OR REPLACE FUNCTION public.handle_new_auth_user()
RETURNS TRIGGER
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
BEGIN
  INSERT INTO public.users (id, email, full_name)
  VALUES (
    NEW.id,
    NEW.email,
    COALESCE(NEW.raw_user_meta_data->>'full_name', NEW.raw_user_meta_data->>'name')
  )
  ON CONFLICT (id) DO UPDATE
    SET email = EXCLUDED.email,
        full_name = COALESCE(EXCLUDED.full_name, public.users.full_name);
  RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS on_auth_user_created ON auth.users;
CREATE TRIGGER on_auth_user_created
  AFTER INSERT OR UPDATE ON auth.users
  FOR EACH ROW EXECUTE FUNCTION public.handle_new_auth_user();

-- ─── Enable RLS on all tenant-scoped tables ─────────────────────────────────
ALTER TABLE public.tenants               ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.users                 ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.memberships           ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.subscriptions         ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.channex_properties    ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.property_groups       ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.properties            ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.bookings              ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.sync_jobs             ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.message_templates     ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.messages              ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.review_templates      ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.reviews               ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.audit_log             ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.webhook_deliveries    ENABLE ROW LEVEL SECURITY;

-- ─── SELECT policies ─────────────────────────────────────────────────────────

-- users: only your own row
CREATE POLICY users_self_select ON public.users
  FOR SELECT USING (id = auth.uid());

-- tenants: only tenants you belong to
CREATE POLICY tenants_member_select ON public.tenants
  FOR SELECT USING (id IN (SELECT public.current_user_tenant_ids()));

-- memberships: rows where you are the user, OR rows in tenants you belong to
CREATE POLICY memberships_self_or_tenant_select ON public.memberships
  FOR SELECT USING (
    user_id = auth.uid()
    OR tenant_id IN (SELECT public.current_user_tenant_ids())
  );

-- All other tenant-scoped tables: scoped by tenant_id
CREATE POLICY subscriptions_tenant_select ON public.subscriptions
  FOR SELECT USING (tenant_id IN (SELECT public.current_user_tenant_ids()));

CREATE POLICY channex_properties_tenant_select ON public.channex_properties
  FOR SELECT USING (tenant_id IN (SELECT public.current_user_tenant_ids()));

CREATE POLICY property_groups_tenant_select ON public.property_groups
  FOR SELECT USING (tenant_id IN (SELECT public.current_user_tenant_ids()));

CREATE POLICY properties_tenant_select ON public.properties
  FOR SELECT USING (tenant_id IN (SELECT public.current_user_tenant_ids()));

CREATE POLICY bookings_tenant_select ON public.bookings
  FOR SELECT USING (tenant_id IN (SELECT public.current_user_tenant_ids()));

CREATE POLICY sync_jobs_tenant_select ON public.sync_jobs
  FOR SELECT USING (tenant_id IN (SELECT public.current_user_tenant_ids()));

CREATE POLICY message_templates_tenant_select ON public.message_templates
  FOR SELECT USING (tenant_id IN (SELECT public.current_user_tenant_ids()));

CREATE POLICY messages_tenant_select ON public.messages
  FOR SELECT USING (tenant_id IN (SELECT public.current_user_tenant_ids()));

CREATE POLICY review_templates_tenant_select ON public.review_templates
  FOR SELECT USING (tenant_id IN (SELECT public.current_user_tenant_ids()));

CREATE POLICY reviews_tenant_select ON public.reviews
  FOR SELECT USING (tenant_id IN (SELECT public.current_user_tenant_ids()));

CREATE POLICY audit_log_tenant_select ON public.audit_log
  FOR SELECT USING (tenant_id IN (SELECT public.current_user_tenant_ids()));

CREATE POLICY webhook_deliveries_tenant_select ON public.webhook_deliveries
  FOR SELECT USING (tenant_id IN (SELECT public.current_user_tenant_ids()));

-- ─── Trigger helper: keep updated_at fresh ──────────────────────────────────
CREATE OR REPLACE FUNCTION public.touch_updated_at()
RETURNS TRIGGER
LANGUAGE plpgsql
AS $$
BEGIN
  NEW.updated_at = NOW();
  RETURN NEW;
END;
$$;

-- Apply to tables that have an updated_at column
DO $$
DECLARE
  t TEXT;
BEGIN
  FOR t IN
    SELECT unnest(ARRAY[
      'tenants', 'subscriptions', 'channex_properties', 'properties',
      'bookings', 'message_templates'
    ])
  LOOP
    EXECUTE format(
      'DROP TRIGGER IF EXISTS touch_%I ON public.%I; ' ||
      'CREATE TRIGGER touch_%I BEFORE UPDATE ON public.%I ' ||
      'FOR EACH ROW EXECUTE FUNCTION public.touch_updated_at();',
      t, t, t, t
    );
  END LOOP;
END;
$$;
