-- =============================================================================
-- Row-Level Security policies
-- =============================================================================
-- This migration is applied AFTER all table-creation migrations generated by
-- drizzle-kit. Filename is `9999_` so it sorts last.
--
-- Rules:
--   - All tenant-scoped tables have RLS enabled.
--   - A user can SELECT rows of any tenant they belong to (via memberships).
--   - Mutations (INSERT/UPDATE/DELETE) go through our API using the SERVICE
--     ROLE key, which bypasses RLS. The API layer enforces tenant scoping in
--     code, with the database as a defense-in-depth backup.
--   - The `users` table is special: a user can only SELECT their own row.
--
-- If you want users to insert/update directly from the client (e.g. for
-- realtime-driven optimistic UI), add per-table WITH CHECK policies here.
-- =============================================================================

-- ─── Helper: stable function returning the current user's tenant IDs ────────
CREATE OR REPLACE FUNCTION public.current_user_tenant_ids()
RETURNS SETOF UUID
LANGUAGE sql
STABLE
SECURITY DEFINER
SET search_path = public
AS $$
  SELECT tenant_id
  FROM public.memberships
  WHERE user_id = auth.uid()
$$;

-- ─── Mirror Supabase auth.users into public.users on signup ─────────────────
CREATE OR REPLACE FUNCTION public.handle_new_auth_user()
RETURNS TRIGGER
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
BEGIN
  INSERT INTO public.users (id, email, full_name)
  VALUES (
    NEW.id,
    NEW.email,
    COALESCE(NEW.raw_user_meta_data->>'full_name', NEW.raw_user_meta_data->>'name')
  )
  ON CONFLICT (id) DO UPDATE
    SET email = EXCLUDED.email,
        full_name = COALESCE(EXCLUDED.full_name, public.users.full_name);
  RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS on_auth_user_created ON auth.users;
CREATE TRIGGER on_auth_user_created
  AFTER INSERT OR UPDATE ON auth.users
  FOR EACH ROW EXECUTE FUNCTION public.handle_new_auth_user();

-- ─── Enable RLS on all tenant-scoped tables ─────────────────────────────────
ALTER TABLE public.tenants               ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.users                 ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.memberships           ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.subscriptions         ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.channex_properties    ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.property_groups       ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.properties            ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.bookings              ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.sync_jobs             ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.message_templates     ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.messages              ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.review_templates      ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.reviews               ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.audit_log             ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.webhook_deliveries    ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.teammates                 ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.cleaning_checklists       ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.cleaning_checklist_items  ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.cleaning_rules            ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.cleaning_messages         ENABLE ROW LEVEL SECURITY;

-- Tables added after the initial RLS pass. They are BACKEND-ONLY (not in the
-- realtime publication, never queried directly by the browser — all access goes
-- through the API on the service-role/postgres connection, which bypasses RLS).
-- So RLS is enabled with NO SELECT policy = default-deny for anon/authenticated.
-- (Closes Supabase `rls_disabled_in_public` critical advisory, 2026-05-31.)
ALTER TABLE public.rate_overrides            ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.ari_pending               ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.message_variables         ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.message_variable_values   ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.message_booking_overrides ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.message_template_listings ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.outbound_reviews          ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.cleaning_calendars        ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.cleaning_rule_listings    ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.cleaning_rule_teammates   ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.tenant_sms_countries      ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.guest_messages            ENABLE ROW LEVEL SECURITY;

-- ─── SELECT policies ─────────────────────────────────────────────────────────
-- Idempotent pattern: DROP IF EXISTS, then CREATE.

DROP POLICY IF EXISTS users_self_select ON public.users;
CREATE POLICY users_self_select ON public.users
  FOR SELECT USING (id = auth.uid());

DROP POLICY IF EXISTS tenants_member_select ON public.tenants;
CREATE POLICY tenants_member_select ON public.tenants
  FOR SELECT USING (id IN (SELECT public.current_user_tenant_ids()));

DROP POLICY IF EXISTS memberships_self_or_tenant_select ON public.memberships;
CREATE POLICY memberships_self_or_tenant_select ON public.memberships
  FOR SELECT USING (
    user_id = auth.uid()
    OR tenant_id IN (SELECT public.current_user_tenant_ids())
  );

DROP POLICY IF EXISTS subscriptions_tenant_select ON public.subscriptions;
CREATE POLICY subscriptions_tenant_select ON public.subscriptions
  FOR SELECT USING (tenant_id IN (SELECT public.current_user_tenant_ids()));

DROP POLICY IF EXISTS channex_properties_tenant_select ON public.channex_properties;
CREATE POLICY channex_properties_tenant_select ON public.channex_properties
  FOR SELECT USING (tenant_id IN (SELECT public.current_user_tenant_ids()));

DROP POLICY IF EXISTS property_groups_tenant_select ON public.property_groups;
CREATE POLICY property_groups_tenant_select ON public.property_groups
  FOR SELECT USING (tenant_id IN (SELECT public.current_user_tenant_ids()));

DROP POLICY IF EXISTS properties_tenant_select ON public.properties;
CREATE POLICY properties_tenant_select ON public.properties
  FOR SELECT USING (tenant_id IN (SELECT public.current_user_tenant_ids()));

DROP POLICY IF EXISTS bookings_tenant_select ON public.bookings;
CREATE POLICY bookings_tenant_select ON public.bookings
  FOR SELECT USING (tenant_id IN (SELECT public.current_user_tenant_ids()));

DROP POLICY IF EXISTS sync_jobs_tenant_select ON public.sync_jobs;
CREATE POLICY sync_jobs_tenant_select ON public.sync_jobs
  FOR SELECT USING (tenant_id IN (SELECT public.current_user_tenant_ids()));

DROP POLICY IF EXISTS message_templates_tenant_select ON public.message_templates;
CREATE POLICY message_templates_tenant_select ON public.message_templates
  FOR SELECT USING (tenant_id IN (SELECT public.current_user_tenant_ids()));

DROP POLICY IF EXISTS messages_tenant_select ON public.messages;
CREATE POLICY messages_tenant_select ON public.messages
  FOR SELECT USING (tenant_id IN (SELECT public.current_user_tenant_ids()));

DROP POLICY IF EXISTS review_templates_tenant_select ON public.review_templates;
CREATE POLICY review_templates_tenant_select ON public.review_templates
  FOR SELECT USING (tenant_id IN (SELECT public.current_user_tenant_ids()));

DROP POLICY IF EXISTS reviews_tenant_select ON public.reviews;
CREATE POLICY reviews_tenant_select ON public.reviews
  FOR SELECT USING (tenant_id IN (SELECT public.current_user_tenant_ids()));

DROP POLICY IF EXISTS audit_log_tenant_select ON public.audit_log;
CREATE POLICY audit_log_tenant_select ON public.audit_log
  FOR SELECT USING (tenant_id IN (SELECT public.current_user_tenant_ids()));

DROP POLICY IF EXISTS webhook_deliveries_tenant_select ON public.webhook_deliveries;
CREATE POLICY webhook_deliveries_tenant_select ON public.webhook_deliveries
  FOR SELECT USING (tenant_id IN (SELECT public.current_user_tenant_ids()));

DROP POLICY IF EXISTS teammates_tenant_select ON public.teammates;
CREATE POLICY teammates_tenant_select ON public.teammates
  FOR SELECT USING (tenant_id IN (SELECT public.current_user_tenant_ids()));

DROP POLICY IF EXISTS cleaning_checklists_tenant_select ON public.cleaning_checklists;
CREATE POLICY cleaning_checklists_tenant_select ON public.cleaning_checklists
  FOR SELECT USING (tenant_id IN (SELECT public.current_user_tenant_ids()));

DROP POLICY IF EXISTS cleaning_checklist_items_tenant_select ON public.cleaning_checklist_items;
CREATE POLICY cleaning_checklist_items_tenant_select ON public.cleaning_checklist_items
  FOR SELECT USING (tenant_id IN (SELECT public.current_user_tenant_ids()));

DROP POLICY IF EXISTS cleaning_rules_tenant_select ON public.cleaning_rules;
CREATE POLICY cleaning_rules_tenant_select ON public.cleaning_rules
  FOR SELECT USING (tenant_id IN (SELECT public.current_user_tenant_ids()));

DROP POLICY IF EXISTS cleaning_messages_tenant_select ON public.cleaning_messages;
CREATE POLICY cleaning_messages_tenant_select ON public.cleaning_messages
  FOR SELECT USING (tenant_id IN (SELECT public.current_user_tenant_ids()));

-- ─── Trigger helper: keep updated_at fresh ──────────────────────────────────
CREATE OR REPLACE FUNCTION public.touch_updated_at()
RETURNS TRIGGER
LANGUAGE plpgsql
AS $$
BEGIN
  NEW.updated_at = NOW();
  RETURN NEW;
END;
$$;

-- Apply to tables that have an updated_at column
DO $$
DECLARE
  t TEXT;
BEGIN
  FOR t IN
    SELECT unnest(ARRAY[
      'tenants', 'subscriptions', 'channex_properties', 'properties',
      'bookings', 'message_templates',
      'teammates', 'cleaning_checklists', 'cleaning_rules'
    ])
  LOOP
    EXECUTE format(
      'DROP TRIGGER IF EXISTS touch_%I ON public.%I; ' ||
      'CREATE TRIGGER touch_%I BEFORE UPDATE ON public.%I ' ||
      'FOR EACH ROW EXECUTE FUNCTION public.touch_updated_at();',
      t, t, t, t
    );
  END LOOP;
END;
$$;
